// <auto-generated />
namespace TechNote.DataAccess.SQL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class changeDate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changeDate));
        
        string IMigrationMetadata.Id
        {
            get { return "201907062210550_changeDate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
